<?php
function env($constant, $default=null) {
	return @constant($constant) ?? $default;
}
DEFINE('APP_URL', 'payments.apuestatotal.app');

DEFINE('DB_HOST', 'db-gestion.cyxi90mjli4a.us-east-1.rds.amazonaws.com');
DEFINE('DB_PORT', '3306');

DEFINE('DB_DATABASE', 'at_payments_prueba');
DEFINE('DB_USERNAME', 'admin');
DEFINE('DB_PASSWORD', 'CxxW34GOV9fgw0Aj3f1G');

DEFINE('DB_DATABASE_KUSHKI', 'at_kushki');
DEFINE('DB_USERNAME_KUSHKI', 'admin');
DEFINE('DB_PASSWORD_KUSHKI', 'CxxW34GOV9fgw0Aj3f1G');

DEFINE('DB_DATABASE_KUSHKIPAYMENT', 'bc_kushkipayment');
DEFINE('DB_USERNAME_KUSHKIPAYMENT', 'admin');
DEFINE('DB_PASSWORD_KUSHKIPAYMENT', 'CxxW34GOV9fgw0Aj3f1G');

DEFINE('BC_KUSHKI_SECRET_KEY', 'wwaw4TbqSrO24gH22');

DEFINE('API_V2_TOKEN','');
DEFINE('KUSHKI_MERCHANT_ID', '');
DEFINE('KUSHKI_WEBHOOK_SIGNATURE', '');

///prometeo
DEFINE('API_KEY_PROMETEO','SKEyYnMt1OGIoMX0gpAy0xPJLrgh2e5p8jp3vGrZyjqO1wbuIJDKPuSHKxpIFynA');
DEFINE('WIDGET_PROMTEO','aa2b08c8-b9e1-4fb2-a971-c3ec850c5692');

///payphone
DEFINE('IDENTIFICADOR_PAYPHONE','2LEbk8KZUiZLGVrDyvnA');
DEFINE('ID_CLIENTE_PAYPHONE','s3MjKMpiw0uYl7cZtiYXEA');
DEFINE('CLAVE_SECRETA_PAYPHONE','dJCIrvhV0ECUv7nnJVg');
DEFINE('CONTRASEÑA_CODIFICACION_PAYPHONE','2febd512ea3841b09169ccc92b2a0ffb');
DEFINE('TOKEN_PAYPHONE','OEcjRT2DJZiPFB7M5_w54ZDvp5P9VxKMuXQdzregqH1HtrZqoVUqqCYaDL0TNEfteI_kxMfd_uNZaAvR1y5L799hrAbgGmZCZkoOsMEN-GHNL4JsdQeG3-V3VBWwaeD1ytydsrpSBh7GF8ZPsgMxUOjZB0PNwbyRxMRIL6Qt3RPHLOsjSqoBD94DN-6Gps5yxOwIbz-DLuDofgMAIj8SeHUqQPxMwu71pFkziQJFY3wPcZOvJnyCAXnnUK_vgipHB9jGjR8vJouA_I-yUOzPFf3MHoFE9N_1OnjZgLnGwJKfdjMIS_QzCg5NwoJAtRugqBMF_g');
DEFINE('STOREID_PAYPHONE','4d7f01a8-fea9-4bfb-8de5-89ee5eaa7032');
DEFINE('RESPONSEURL_PAYPHONE', 'https://payments.totalbet.com/Payments-SSD/payphonenots.php');

///limite de pago 
DEFINE('DEPOSIT_LIMITS', '1,500');
/// Direccion del proyecto
define('ROOT_PATH', $_SERVER['DOCUMENT_ROOT']);

?>